/**
 * Modifies the Jest's Expect error message for display in the IDE
 *
 * @param {Error} error Error, generated by Jest's Expect
 * @param {String} errorMessage An error message that will be displayed to the user in the IDE
 * @param {Boolean} rmStack Specifies whether stack trace errors will be deleted
 */
export function customizeError(error, errorMessage, rmStack = false) {
    error.message = error.message.replace(/.*\n/, errorMessage);
    if (rmStack) {
        error.stack = null;
    }
}
